### ISSUE TITLE
Connecting to non telnet servers

### ISSUE THREAD

**Issue by alexdelprete** [AlaBouali/xtelnet#5]
Ciao Ala,

I really like the simple approach your library takes in managing "telnet" servers.

I wanted to use it to connect to my energy monitoring device, that doesn't have a proper interface to pull data out, but its official mobile app pulls data out of it via telnet on port 5001. So it actually has a raw terminal listening on port 5001 and it answers to some commands, and it returns data using `"ready..."` as end of response.

I can use standard telnet in linux/windows manually, it works as expected. Now I wanted to write a small python script to do it automatically.

The problem is that when I use your library, I receive the error message `"An error occurred: Not a telnet service"`.

I think it probably recognizes there are no control strings etc, so it refuses to operate.

Is there a way to skip that check? Maybe an option, so I can make it work also with non-telnet servers, but "stupid" socket servers like this.

This is the code I'm trying:

```python
async def main():
    host = "elios4u.axel.dom"  # IP or hostname
    port = 5001  # elios4You default port

    try:
        telnet = xtelnet.session()
        telnet.connect(u=host, p=port, timeout=5, debug_level=1)
        resp = telnet.execute("@DAT")
        print(resp)
        telnet.close()
        telnet.destroy()
```

**Comment by AlaBouali** [comment]
hello alex,

i will update the library so it can skip verifying if the service is "telnet" or not. so it can connect and hold the connection between you and the servers.

i will notify you when it is ready !

**Comment by alexdelprete** [comment]
Thank you very much, it will be helpful for raw tcp connections. For now, I've used the old trusted telnetlib, even if deprecated (I imported it in the project directly), and finally everything started working properly. telnetlib3 is really unreliable, a lot of weird errors.

Very kind to accept the suggestion, I appreciate it.

**Comment by AlaBouali** [comment]
hello there my friend,

i apologize for the delay, i didn't find any clear documentation how to parse and respond to telnet negotiations but it turns out that i can skip them since they are only used to better present the output on the user's terminal. since xtelnet is not presenting them , i skipped that and tested it on several telnet servers and the results were promising ! please check the new documentation and much cleaner and readable code.

thank you for using xtelnet.

**Comment by AlaBouali** [comment]
note: i added a connect parameter just for you ! lol i hope it helps you.

**Comment by alexdelprete** [comment]
> i added a connect parameter just for you ! lol i hope it helps you.

My friend, thank you so much for implementing this. I'll test it as soon as possible and report back.

I really appreciate your kindness and help.

**Comment by AlaBouali** [comment]
you are welcome ! take your time.

**Comment by alexdelprete** [comment]
my friend...would it be possible to implement a read_until() function in telnet_client like the one in telnetlib? It's ideal when dealing with "raw"/"stupid" tcp servers that wait for commands, execute them, return output, and then provide a "cmd_received" string that can be used to acknowledge the end of the command execution so you don't need to wait for timeout before sending next command.

```python
    def read_until(self, match, timeout=None):
        """Read until a given string is encountered or until timeout.

        When no match is found, return whatever is available instead,
        possibly the empty string.  Raise EOFError if the connection
        is closed and no cooked data is available.

        """
        n = len(match)
        self.process_rawq()
        i = self.cookedq.find(match)
        if i >= 0:
            i = i + n
            buf = self.cookedq[:i]
            self.cookedq = self.cookedq[i:]
            return buf
        if timeout is not None:
            deadline = _time() + timeout
        with _TelnetSelector() as selector:
            selector.register(self, selectors.EVENT_READ)
            while not self.eof:
                if selector.select(timeout):
                    i = max(0, len(self.cookedq) - n)
                    self.fill_rawq()
                    self.process_rawq()
                    i = self.cookedq.find(match, i)
                    if i >= 0:
                        i = i + n
                        buf = self.cookedq[:i]
                        self.cookedq = self.cookedq[i:]
                        return buf
                if timeout is not None:
                    timeout = deadline - _time()
                    if timeout < 0:
                        break
        return self.read_very_lazy()
```

**Comment by AlaBouali** [comment]
please check the new updates:

- added telnet nogotiations
- "read_until" method to the telnet client
- "read_until_match" parameter in "execute" method, for your case to execute the command and wait till a specific string returned

try the new version and give me an update !

**Comment by alexdelprete** [comment]
> try the new version and give me an update !

My friend, thank you so much!!

Hadn't time to test it, but will give you a feedback once I modify my code. :)
